### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by richhosek** [Insane-Instructors/Proteus#3]
## Authentication
As a homeowner, I want to be able to log in with my personal credentials so that I can secure access to my home automation.

## Acceptance Criteria
- [ ] first open page, taken to Wink Log in
- [ ] After login at Wink, I can access my home devices

## Tasks
- [ ] Get key for Wink API
- [ ] Set up return URLs
- [ ] Test in Postman

**Comment by richhosek** [comment]
[ ] Get key for Wink API
[ ] Set up return URLs
[ ] Test in Postman
